package validator;

import java1.validator.OrderValidator;
import java1.model.Order;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class OrderValidatorTest {

    private OrderValidator validator;
    private Order order;

    @BeforeEach
    void setUp() {
        validator = new OrderValidator();
        order = new Order("123", "Иван Иванов", "Ноутбук", 2, false);
    }

    @Test
    void testValidOrder() {
        assertTrue(validator.isValid(order));
    }

    @Test
    void testNullCustomerName() {
        order.setCustomerName(null);
        assertFalse(validator.isValid(order));
    }

    @Test
    void testEmptyCustomerName() {
        order.setCustomerName("");
        assertFalse(validator.isValid(order));
    }

    @Test
    void testNullProductDescription() {
        order.setProductDescription(null);
        assertFalse(validator.isValid(order));
    }

    @Test
    void testEmptyProductDescription() {
        order.setProductDescription("");
        assertFalse(validator.isValid(order));
    }

    @Test
    void testNullId() {
        order.setId(null);
        assertFalse(validator.isValid(order));
    }

    @Test
    void testEmptyId() {
        order.setId("");
        assertFalse(validator.isValid(order));
    }

    @Test
    void testNegativeQuantity() {
        order.setQuantity(-5);
        assertFalse(validator.isValid(order));
    }

    @Test
    void testZeroQuantity() {
        order.setQuantity(0);
        assertFalse(validator.isValid(order));
    }

    @Test
    void testNullOrder() {
        assertFalse(validator.isValid(null));
    }

    @Test
    void testAutoGeneratedId() {
        Order newOrder = new Order("Петр Петров", "Телефон", 1, false);
        assertNotNull(newOrder.getId());
        assertTrue(validator.isValid(newOrder));
    }

    @Test
    void testUrgentOrder() {
        Order urgentOrder = new Order("urgent-id", "Иван Иванов", "Товар", 1, true);
        assertTrue(urgentOrder.isUrgent());
        assertTrue(validator.isValid(urgentOrder));
    }

    @Test
    void testNormalOrder() {
        Order normalOrder = new Order("normal-id", "Иван Иванов", "Товар", 1, false);
        assertFalse(normalOrder.isUrgent());
        assertTrue(validator.isValid(normalOrder));
    }

    @Test
    void testIsUrgentOrderReturnsFalseForNormalOrder() {
        assertFalse(validator.isUrgentOrder(order));
    }

    @Test
    void testIsUrgentOrderReturnsTrueForUrgentOrder() {
        Order urgentOrder = new Order("456", "Jane Smith", "Phone", 1, true);
        assertTrue(validator.isUrgentOrder(urgentOrder));
    }

    @Test
    void testIsUrgentOrderReturnsFalseForNull() {
        assertFalse(validator.isUrgentOrder(null));
    }

    @Test
    void testValidateAcceptsValidUrgentOrder() {
        Order urgentOrder = new Order("urgent-1", "Urgent Customer", "Urgent Product", 1, true);
        assertTrue(validator.isValid(urgentOrder));
    }

    @Test
    void testBlankCustomerName() {
        order.setCustomerName("   ");
        assertFalse(validator.isValid(order));
    }

    @Test
    void testValidateReturnsErrors() {
        Order invalidOrder = new Order();
        invalidOrder.setId(null);
        invalidOrder.setCustomerName(null);
        invalidOrder.setProductDescription(null);
        invalidOrder.setQuantity(0);

        var errors = validator.validate(invalidOrder);
        assertFalse(errors.isEmpty());
        assertTrue(errors.size() >= 3);
    }

    @Test
    void testVeryLongCustomerName() {
        String longName = "A".repeat(1000);
        Order order = new Order("1", longName, "Product", 1, false);
        assertTrue(validator.isValid(order));
    }

    @Test
    void testVeryLongProductDescription() {
        String longDesc = "B".repeat(2000);
        Order order = new Order("1", "Customer", longDesc, 1, false);
        assertTrue(validator.isValid(order));
    }

    @Test
    void testMaxQuantity() {
        Order order = new Order("1", "Customer", "Product", Integer.MAX_VALUE, false);
        assertTrue(validator.isValid(order));
    }

    @Test
    void testSpecialCharactersInName() {
        Order order = new Order("1", "!@#$%^&*()", "Product", 1, false);
        assertTrue(validator.isValid(order));
    }

    @Test
    void testSpecialCharactersInProduct() {
        Order order = new Order("1", "Customer", "!@#$%^&*()", 1, false);
        assertTrue(validator.isValid(order));
    }

    @Test
    void testWhitespaceOnlyCustomerName() {
        Order order = new Order("1", "   ", "Product", 1, false);
        assertFalse(validator.isValid(order));
    }

    @Test
    void testWhitespaceOnlyProductDescription() {
        Order order = new Order("1", "Customer", "   ", 1, false);
        assertFalse(validator.isValid(order));
    }

    @Test
    void testIdWithSpaces() {
        Order order = new Order("1 2 3", "Customer", "Product", 1, false);
        assertTrue(validator.isValid(order));
    }

    @Test
    void testNumericCustomerName() {
        Order order = new Order("1", "12345", "Product", 1, false);
        assertTrue(validator.isValid(order));
    }

    @Test
    void testSingleCharacterName() {
        Order order = new Order("1", "A", "Product", 1, false);
        assertTrue(validator.isValid(order));
    }

}