package validator;

import java1.validator.OrderValidator;
import java1.model.Order;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class OrderValidatorTest {

    private OrderValidator validator;
    private Order order;

    @BeforeEach
    void setUp() {
        validator = new OrderValidator();
        order = new Order("123", "Иван Иванов", "Ноутбук", 2, false);
    }

    @Test
    void testValidOrder() {
        assertTrue(validator.isValid(order));
    }

    @Test
    void testNullCustomerName() {
        order.setCustomerName(null);
        assertFalse(validator.isValid(order));
    }

    @Test
    void testEmptyCustomerName() {
        order.setCustomerName("");
        assertFalse(validator.isValid(order));
    }

    @Test
    void testNullProductDescription() {
        order.setProductDescription(null);
        assertFalse(validator.isValid(order));
    }

    @Test
    void testEmptyProductDescription() {
        order.setProductDescription("");
        assertFalse(validator.isValid(order));
    }

    @Test
    void testNullId() {
        order.setId(null);
        assertFalse(validator.isValid(order));
    }

    @Test
    void testEmptyId() {
        order.setId("");
        assertFalse(validator.isValid(order));
    }

    @Test
    void testNegativeQuantity() {
        order.setQuantity(-5);
        assertFalse(validator.isValid(order));
    }

    @Test
    void testZeroQuantity() {
        order.setQuantity(0);
        assertFalse(validator.isValid(order));
    }

    @Test
    void testNullOrder() {
        assertFalse(validator.isValid(null));
    }

    @Test
    void testAutoGeneratedId() {
        Order newOrder = new Order("Петр Петров", "Телефон", 1, false);
        assertNotNull(newOrder.getId());
        assertTrue(validator.isValid(newOrder));
    }

    @Test
    void testUrgentOrder() {
        Order urgentOrder = new Order("urgent-id", "Иван Иванов", "Товар", 1, true);
        assertTrue(urgentOrder.isUrgent());
        assertTrue(validator.isValid(urgentOrder));
    }

    @Test
    void testNormalOrder() {
        Order normalOrder = new Order("normal-id", "Иван Иванов", "Товар", 1, false);
        assertFalse(normalOrder.isUrgent());
        assertTrue(validator.isValid(normalOrder));
    }
}