package test.validator;

import java1.model.Order;
import java1.validator.OrderValidator;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class OrderValidatorTest {
    private OrderValidator validator;

    @BeforeEach
    void setUp() {
        validator = new OrderValidator();
    }

    @Test
    void testValidOrder() {
        Order order = new Order("id", "John Doe", "Laptop", 2, false);
        assertTrue(validator.isValid(order));
        assertTrue(validator.validate(order).isEmpty());
    }

    @Test
    void testNullCustomerName() {
        Order order = new Order("id-1", null, "Product", 1, false);
        List<String> errors = validator.validate(order);
        assertFalse(errors.isEmpty());
        assertTrue(errors.stream().anyMatch(e -> e.contains("Customer name")));
    }

    @Test
    void testEmptyCustomerName() {
        Order order = new Order("id-1", "", "Product", 1, false);
        List<String> errors = validator.validate(order);
        assertFalse(errors.isEmpty());
        assertTrue(errors.stream().anyMatch(e -> e.contains("Customer name")));
    }

    @Test
    void testNullProductDescription() {
        Order order = new Order("id-1", "John Doe", null, 1, false);
        List<String> errors = validator.validate(order);
        assertFalse(errors.isEmpty());
        assertTrue(errors.stream().anyMatch(e -> e.contains("Product description")));
    }

    @Test
    void testEmptyProductDescription() {
        Order order = new Order("id-1", "John Doe", "", 1, false);
        List<String> errors = validator.validate(order);
        assertFalse(errors.isEmpty());
        assertTrue(errors.stream().anyMatch(e -> e.contains("Product description")));
    }

    @Test
    void testNullOrder() {
        List<String> errors = validator.validate(null);
        assertFalse(errors.isEmpty());
        assertEquals("Order cannot be null", errors.get(0));
    }

    @Test
    void testAutoGeneratedId() {
        Order order = new Order("John Doe", "Product", 1, false);
        assertNotNull(order.getId());
        assertFalse(order.getId().isEmpty());
        assertTrue(validator.isValid(order));
    }

    @Test
    void testUrgentOrder() {
        Order urgentOrder = new Order("urgent-id", "John Doe", "Product", 1, true);
        assertTrue(urgentOrder.isUrgent());
        assertTrue(validator.isValid(urgentOrder));
    }

    @Test
    void testNormalOrder() {
        Order normalOrder = new Order("normal-id", "John Doe", "Product", 1, false);
        assertFalse(normalOrder.isUrgent());
        assertTrue(validator.isValid(normalOrder));
    }
}